blank_issues_enabled: false
contact_links:
  - name: Questions, feature requests, and general discussion
    url: https://github.com/home-health-hub/viatom-o2ring-ble/discussions
    about: For anything that isn't a bug report, please use Discussions instead.
